# Generated by Django 5.0.6 on 2024-07-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_alter_receipes_public_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipes',
            name='public_private',
        ),
    ]
