# Generated by Django 5.0.6 on 2024-07-09 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_remove_receipes_public_private'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receipes',
            name='public_private',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
